### PR TITLE
Add Login, resignation and routing with devise

### LINKED ISSUE #1: [ 2pt]- Login page and registration page
Should be built with Devise.

### PR DESCRIPTION
**Pull request by AbdusSattar-70**
### In this PR, I have added the following:

- [ ] Added devise, Cancancan for authentication and authorization.

[Add login and registration page with devise](https://github.com/peterdtitan/food-recipe-app/pull/14/commits/dab0abb34e38bbf0aed865a181ff0124681d117b)

[Generate cancan ability class & add user email](https://github.com/peterdtitan/food-recipe-app/pull/14/commits/c038713cfb7cbe255780ee5ffca07ec7232b873d)
[Set homepage and login and registration page modify](https://github.com/peterdtitan/food-recipe-app/pull/14/commits/fd06bbe09ee65103f54ab57c2c0824cfbd27ad75)
[Add style for login page](https://github.com/peterdtitan/food-recipe-app/pull/14/commits/fb4f03f3794089d3fd5aad0b78bda0b0fe678e1f)
## After merging the PR will solve the issue #1

### CODE REVIEW

**Comment by peterdtitan** [comment]
Hi @AbdusSattar-70 , 

Good job so far!
There are some issues that you still need to work on to go to the next part of the project but you are almost there!



## Highlights :heavy_check_mark: 
- [x] Git flow is used correctly ✅ 
- [x] Functionality is well implemented.   ✅ 
- [x] No failing linters ✅  
- [ ]  PR does not have a descriptive summary wrong ❌ 


## Required Changes ♻️

- [Required] I think it would be helpful if you provided a descriptive PR instead of a blank one. Good job on writing a descriptive name though.



_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by AbdusSattar-70** [comment]
> Hi @AbdusSattar-70 ,
> 
> Good job so far! There are some issues that you still need to work on to go to the next part of the project but you are almost there!
> 
> ## Highlights ✔️
> * [x]  Git flow is used correctly ✅
> * [x]  Functionality is well implemented.   ✅
> * [x]  No failing linters ✅
> * [ ]   PR does not have a descriptive summary wrong ❌
> 
> ## Required Changes ♻️
> * [Required] I think it would be helpful if you provided a descriptive PR instead of a blank one. Good job on writing a descriptive name though.



### Thank you, @peterdtitan, for your early feedback. However, I would appreciate it if you could provide a review once the assignment is complete. Currently, I am still working on the branch, and your review would be more valuable and comprehensive once I have finished the task.

**Review by peterdtitan — APPROVED** [review]
STATUS APPROVED ✔️ 🎉 ✔️

Hi @AbdusSattar-70,

Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉

Highlights

 Setup devise correctly ✔️
 No linters errors ✔️
 Correct Gitflow ✔️
Optional suggestions

Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were missed by the previous reviewer and addressing them will really improve your application.

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please remember to tag me in your question so I can receive the notification.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by AbdusSattar-70** [comment]
@peterdtitan Thanks for your insightful review.😍😍

**Pull request merged**
